github:
  token: "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"
  url: "https://api.github.com/"
  branch: "master"

slack:
  token: "xoxb-4223066129283-4220316106149-zr0tiUKeBPRb9Sk7cTxjtD40"
  channel: "#github"